pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'JAVA_8'
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/gerdzso/cgm.git'
                
                // Run Maven on a Unix agent.
                bat "mvn -f ./faq/pom.xml clean install"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'faq/target/*.jar'
                }
            }
        }
    }
}